### ISSUE TITLE
Continuous conditions

### ISSUE THREAD

**Issue by KidElectric** [const-ae/lemur#3]
Hello -- very cool package! I have a question about how this framework handles continuous conditions. Are all conditions treated as factors? I tried fitting with some continuous conditions but I got the sense they were converted to factors internally. Is there a way to perform something like:
`fit <- lemur(sce, design = ~ Patient + Arm + cont.var`
 `fit <- test_de(fit, contrast = cond(Arm = 'A', cont.var > 10 ) - cond(Arm = 'A', cont.var < 5))`

Or maybe a related question is if continuous variables were binned into a set of factors -> does factor level order have any bearing on how LEMUR performs fit?

I realize some of these are likely naive questions! Thank you for your time!

**Comment by const-ae** [comment]
Hi, 
thanks for giving lemur a try :)

> Are all conditions treated as factors? I tried fitting with some continuous conditions but I got the sense they were converted to factors internally

No, continuous covariates are treated continuously. There is one limitation which is due to my current implementation that each continuous value needs to have at least `n_embedding` instances, but this is typically true for single-cell data because you still measure many cells at a time point / drug concentration / temperature / whatever your continuous covariate is.

> `fit <- test_de(fit, contrast = cond(Arm = 'A', cont.var > 10 ) - cond(Arm = 'A', cont.var < 5))`

I see what you are trying to accomplish here, but a specification such as `cont.var > 10` in the contrast is not supported. The technical reason is that `lemur` internally translates the contrast specification into a contrast vector (e.g., `c(0, 0, 1, 0, -1)`) that is used in `multcomp`, `limma`, `edgeR`, or `DESeq2`. The `cond(...) - cond(...)` specification is just syntactic sugar.

I drew a small schematic that shows how the contrast specification would look like for a linear model with a continuous covariate. 

![IMG_20230317_192233](https://user-images.githubusercontent.com/5359014/225987893-c90a8c62-6051-4f90-ba25-cfe5a0a50262.jpg)

The same kind of logic applies also in `lemur`.  So you could change the second line to:
```r
fit <- test_de(fit, contrast = cond(Arm = 'A', cont.var = 10) - cond(Arm = 'A', cont.var = 5))
```

It is important to note that only the log-fold change depends on the chosen values for a continuous covariate in the contrast, the significance test is independent because doubling the log-fold change also doubles the associated standard error (i.e., `cond(Arm = 'A', cont.var = 10) - cond(Arm = 'A', cont.var = 5))` and `cond(Arm = 'A', cont.var = 0) - cond(Arm = 'A', cont.var = 1))` should give the same p-values if `cont.var` is linear in the model).

Best,
Constantin

**Comment by KidElectric** [comment]
Thank you this is very helpful!
