### ISSUE TITLE
map cell types across the latent embedding: DE testing for gene sets?

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [const-ae/lemur#8]
I am presenting/discussing the preprint and repo in a journal club in a few minutes and thought of something... Again, pls ignore and close if this is too crazy...

Would it be possible to run the differential expression tests on several genes at a time, rather than a single gene? I was thinking maybe one could use cell type signatures in order to map cell types across the latent embedding and facilitate interpretation.

**Comment by PedroMilanezAlmeida** [comment]
Ugh, closing it, had nothing to do with DE analysis...

**Comment by const-ae** [comment]
Sorry, I am at a conference currently and didn't see your issue in time and no worries, I am excited to hear that you found the preprint interesting to discuss in your journal club :)

-----

> Would it be possible to run the differential expression tests on several genes at a time, rather than a single gene?

In theory, yes. A use case for such an approach would be to look at the expression changes across a pathway or for all downstream targets of a transcription factor, rather than a cell type signature. However, this is not an implemented analysis and would require some custom code from the analyst.
